# Generated by Django 4.2.1 on 2023-06-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orell_alexander', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
