# Generated by Django 4.2.1 on 2023-06-29 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_orell_alexander', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
